### ISSUE TITLE
Installing with Poetry does not install VERSION file

### ISSUE THREAD

**Issue by Insighttful** [satyamsoni2211/lazy_alchemy#4]
`>> poetry add lazy_alchemy`

> FileNotFoundError: [Errno 2] No such file or directory: '/home/anon/company/reps/project1/.venv/lib/python3.10/site-packages/lazy_alchemy/VERSION'

Inspecting the lazy_alchemy dir confirms the VERSION file is not present.

**Comment by Insighttful** [comment]
Temporary workaround:
`>> echo '0.0.2' > /home/anon/company/reps/project1/.venv/lib/python3.10/site-packages/lazy_alchemy/VERSION`

**Comment by Insighttful** [comment]
Poetry: https://python-poetry.org/

**Comment by jonbiemond** [comment]
Also an issue when installed using Pipenv.

**Comment by satyamsoni2211** [comment]
@Insighttful @jonbiemond  Can you Fix this and raise a PR ? We would also need to increment minor patch. Can you also help migrate this to poetry ? I suppose than it would be supported for all the environments.

**Comment by satyamsoni2211** [comment]
@vivekkeshore

**Comment by jonbiemond** [comment]
Looks like it might be as simple as adding `include_package_data=True` to `setup()` in setup.py. I'll apply the fix and test. https://stackoverflow.com/questions/50879668/python-setup-py-some-files-are-missing
